# need to create a postgres instance first
# https://fly.io/docs/reference/postgres/


app = "stacks-blockchain-api" # app name
# kill_signal = "SIGTERM" # kill signal to send. default is SIGINT
kill_timeout = 60 #  how long to wait for shutdown

[build]
    dockerfile = "stacks-blockchain-api.Dockerfile"

[deploy]
    strategy = "bluegreen"

[env]
      PG_HOST = ""
      PG_PORT = ""
      PG_DATABASE = ""
      PG_USER = ""
      PG_PASSWORD = ""
      STACKS_CORE_EVENT_PORT= "3700"
      STACKS_CORE_EVENT_HOST = "0.0.0.0"
      STACKS_BLOCKCHAIN_API_PORT = "3999"
      STACKS_BLOCKCHAIN_API_HOST = "0.0.0.0"
      STACKS_BLOCKCHAIN_API_DB = "pg"
      STACKS_CORE_RPC_HOST = "localhost"
      STACKS_CORE_RPC_PORT = "20443"
      NODE_ENV = "production"
      GIT_TAG = "master"
      STACKS_CHAIN_ID = "0x00000001"
      V2_POX_MIN_AMOUNT_USTX = "90000000260"
      STACKS_NETWORK = "mainnet"
      STACKS_EXPORT_EVENTS_FILE = "/root/stacks-blockchain/stacks-node-events.tsv" 

[[services]]
    internal_port = 80
    protocol = "tcp"

    [[services.ports]]
        handlers = ["http"]
        port = "80"

    [[services.ports]]
        handlers = ["tls", "http"]
        port = "443"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5m"
    method = "get"
    path = "/status"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false

[mounts]
source="stacks-blockchain-event-replay"
destination="/root/stacks-blockchain/data"


# https://fly.io/docs/app-guides/multiple-processes/
# https://fly.io/docs/getting-started/multi-region-databases/