app = "stacks-blockchain-3d9f78229768"
kill_timeout = 1200
kill_signal = "SIGTERM"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"

[env]
  RUST_BACKTRACE = "full"
  STACKS_LOG_DEBUG = "0"
  STACKS_NETWORK = "mainnet"

[mounts]
  destination = "/stacks-blockchain"
  source = "stacks_blockchain_data"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5m"
    interval = 30000
    method = "get"
    path = "/status"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false

    [services.http_checks.headers]

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services]]
  internal_port = 20443
  protocol = "tcp"

  [[services.ports]]
    port = "20443"

  [[services.tcp_checks]]
    grace_period = "5m"
    interval = 30000
    timeout = 10000

[[services]]
  internal_port = 20444
  protocol = "tcp"

  [[services.ports]]
    port = "20443"

  [[services.tcp_checks]]
    grace_period = "5m"
    interval = 30000
    timeout = 10000
